//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub priority: Option<String>,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_default: Option<bool>,
    pub user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rust_learn_users::Entity",
        from = "Column::UserId",
        to = "super::rust_learn_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RustLearnUsers,
}

impl Related<super::rust_learn_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RustLearnUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
